import { defineLevel } from '../../engine/defs.js';

// E1M1: THE BASEMENT. You wake up in a rat nest behind the furnace. Time to
// show the other rats who is boss.
//
// Route: the vent cover -> the laundry room -> the hallway -> the workshop
// (Rubber Band Gatling) -> the storage room (blue key, behind the boxes) ->
// the blue door -> the rec room -> the mouse hole by the stairs.
// Secrets: a loose panel in the laundry room's east wall (a vent loop full of
// goodies) and the south wall of the storage room (a closet with the Golden
// Cheese).
export default defineLevel({
  id: 'e1m1',
  mapLabel: 'E1M1',
  name: 'THE BASEMENT',
  music: 'basement',
  sky: 'sky-day',
  par: 90,
  legend: {
    q: { door: 'concrete', secret: true },
    y: { door: 'concrete', secret: true },
    z: { base: 'm', secret: true },
    x: { base: '-', light: 176, secret: true },
  },
  tiles: [
    '                                                 ',
    ' OOUUUOOIOO       OOIOOIOOIOOIOOO                ',
    ' O--------O       O-------------O       VVVVVVVVV',
    ' O--------OVVVVVVVV-------------O       VzzzzzzzV',
    ' O--------GnnnnnnnG=============O       VzzzzzzzY',
    ' O--------OVVVVVVVV=============OVVVVVVVVzzzzzzzV',
    ' O--------O       O=============qzzzzzzzzzzzzzzzY',
    ' O--------O       O=============OVVVVVVVVzzzzzzzV',
    ' OOOOOOOOOO       O=============O       VzzzzzzzV',
    '                  O=============O       VzzzzzzzV',
    '                  O=============O       VVVVVVVVV',
    '                  O=============O                ',
    ' OOOOOOOOOOOONOOOOOOOOOOODOOOOOOOOOOOOOOOOOOOOOOO',
    ' O----------------------------------------------O',
    ' O--=-------=-------=-------=-------=-------=---O',
    ' O----------------------------------------------O',
    ' OOOOOOODOOOOOOOOOOOOOOODOOOOOOOOOOOOOOO1OOOOOOOO',
    ' O==============O---------------w,,,,,,,,,,,,,,,w',
    ' O==============O---------------w,,,,,,,,,,,,,,,w',
    ' O--------------O---------------w,,,,,,,,,,,,,,,w',
    ' O--------------O----=======----w,,,,,,,,,,,,,,,w',
    ' O--------------O----=======----w,,,,,,,,,,,,,,,w',
    ' O--------------O----=======----a,,,,,;;;;;,,,,,w',
    ' O--------------O----=======----w,,,,,;;;;;,,,,,w',
    ' O--------------O----=======----w,,,,,;;;;;,,,,,N',
    ' O--------------O---------------w,,,,,;;;;;,,,,,w',
    ' O--------------O---------------w,,,,,;;;;;,,,,,w',
    ' O--------------O---------------w,,,,,,,,,,,,,,,w',
    ' O--------------Owwwwwwwwwwwwwwww,,,,,,,,,,,,,,,w',
    ' O--------------O               w,,,,,,,,,,,,,,,w',
    ' O--------------O               w,,,,,,,,,,,,,,,w',
    ' O--------------O               w,,,,,,,,,,,,,,,w',
    ' OOOOOOOyOOOOOOOO               wwwwwwwwwwwwXwwww',
    '     oxxxxxo                                     ',
    '     oxxxxxo                                     ',
    '     oxxxxxo                                     ',
    '     ooooooo                                     ',
  ],
  things: [
    '',
    '',
    '                    W  W  W',
    '      ,,,                    L',
    '                                          ; ; ;',
    '    >                    2 M  $',
    '                    + r     d      ; ;',
    '  x     P                                   a',
    '                           r              p',
    '                     ;;M',
    '                   X    r     o',
    '',
    '',
    '  "         r                 i       o       d',
    '      i         !                   r       M',
    '   k                s                      i',
    '',
    '               , I             I',
    '             $                      l ,, ,    F',
    '                    o       1               M',
    '    XX    XX                      @     H',
    '       r                     i',
    '                   i                         m',
    '        X               3',
    '    X       XX                d',
    '       d              s   s        p    V',
    '    r       r           !   r',
    '      X          X             X            $',
    '          X   X                     m         r',
    '   X                                      c',
    '         i                        X   r        S',
    '  b           B',
    '',
    '',
    '        O',
    '      x',
  ],
  triggers: [
    {
      on: 'start',
      do: [{ action: 'message', text: 'YOU WAKE UP BEHIND THE FURNACE. PRESS USE ON THE VENT COVER TO CRAWL OUT.' }],
    },
    {
      on: 'pickup',
      thing: 'pickup-band-gatling',
      do: [{ action: 'message', text: 'THWIP THWIP THWIP! HOLD FIRE TO KEEP FLINGING.' }],
    },
  ],
});
