import { defineLevel } from '../../engine/defs.js';

// E1M2: THE KITCHEN. Up from the basement into a kitchen full of crumbs,
// cheese and rats.
//
// Route: the broom closet -> the back hall -> the kitchen -> the pantry (the
// Soda Bazooka; taking it opens the cupboards) -> the dining room (yellow
// key) -> the yellow door -> the mudroom and the mouse hole.
// The vent over the kitchen joins the back hall to the dining room.
// Secrets: a side duct off the vent (the Golden Cheese) and a panel in the
// dining room's east wall (Bubble Wrap).
export default defineLevel({
  id: 'e1m2',
  mapLabel: 'E1M2',
  name: 'THE KITCHEN',
  music: 'house',
  sky: 'sky-day',
  par: 120,
  legend: {
    u: { door: 'vent-wall', secret: true },
    v: { door: 'wainscot', secret: true },
    q: { door: 'wood-panel', jamb: 'door-jamb', lock: 'remote', tag: 'cupboards' },
    z: { base: 'm', secret: true },
    x: { base: '.', light: 220, secret: true },
  },
  tiles: [
    '             VVVVVVVVVVVVVYVVVVVVVVVVVVVVVVVVVYVVVVVVVVVVVVV       ',
    '             VnnnnnnmnnnnnmnnnnnmnnnnnmnnnnnmnnnnnmnnnnnnnnV       ',
    '             VnVVVVVVVVVVVVVVVVVVVVVuVVVVVVVVVVVVVVVVVVVVVnV       ',
    '             VnV                   VzV                   VnV       ',
    ' ############VGV#####CCCCCCSSCCCCCCCFFFCCCCCCCTWWWWWWWWWWVGVWWW    ',
    ' #......#...........#kkkkkkkkkkkkkkkkkkkkkkkkkT...............W    ',
    ' #......#...........#kkkkkkkkkkkkkkkkkkkkkkkkkT...............W    ',
    ' #......Q...........DkkkjjjjjjjjjjjjjjjjjjjkkkT...............W    ',
    ' #......#...........#kkkjjjjjjjjjjjjjjjjjjjkkkT..rrrrrrrrrrr..W    ',
    ' #......#...........#kkkkkkkkkkkkkkkkkkkkkkkkkN..rrrrrrrrrrr..W    ',
    ' ##########N#########kkkkkkkkkkkkkkkkkkkkkkkkkT..rrrrrrrrrrr..W    ',
    '                    TkkkkkkkkkkkkkkkkkkkkkkkkkT..rrrrrrrrrrr..W    ',
    '                    TkkkkkkkkkkkkkkkkkkkkkkkkkT..rrrrrrrrrrr..A    ',
    '                    TkkkkkkkkCCCCCCCCCkkkkkkkkT..rrrrrrrrrrr..W    ',
    '                    TkkkkkkkkCCCCCCCCCkkkkkkkkD..rrrrrrrrrrr..W    ',
    '                    TkkkkkkkkCCCCCCCCCkkkkkkkkT..rrrrrrrrrrr..WWWWW',
    '                    TkkkkkkkkCCCCCCCCCkkkkkkkkT..rrrrrrrrrrr..WxxxW',
    '                    TkkkkkkkkkkkkkkkkkkkkkkkkkT..rrrrrrrrrrr..WxxxW',
    '                    TkkkkkkkkkkkkkkkkkkkkkkkkkT..rrrrrrrrrrr..vxxxW',
    '                    TkkkkkkkkkkkkkkkkkkkkkkkkkT...............WxxxW',
    '                    TkkkjjjjjjjjjjjjjjjjjjjkkkT...............WxxxW',
    '                    TkkkjjjjjjjjjjjjjjjjjjjkkkT...............WWWWW',
    '                    TkkkkkkkkkkkkkkkkkkkkkkkkkTWWWNWWWNWWWWWWWW    ',
    '                    TkkkkkkkkkkkkkkkkkkkkkkkkkT                    ',
    '                    TkkkkkkkkkkkkkkkkkkkkkkkkkT                    ',
    '                    TkkkkkkkkkkkkkkkkkkkkkkkkkT                    ',
    '                    TCCCCCCDCCTTTTTTTTTT2TTTTTT####                ',
    '                    w.............w #,,,,,,,,,,,,,#                ',
    '                    L.............L #,,,,,,,,,,,,,#                ',
    '                    L.............L #,,,;;;;;;;,,,#                ',
    '                    L.............L #,,,;;;;;;;,,,#                ',
    '                    L.............L #,,,;;;;;;;,,,#                ',
    '                    L.............L #,,,;;;;;;;,,,#                ',
    '                    L.............L #,,,;;;;;;;,,,#                ',
    '                    L.............L #,,,,,,,,,,,,,#                ',
    '                    w.............w #,,,,,,,,,,,,,#                ',
    '                    wwwwqwwwwwqwwww #######X#######                ',
    '                     w....w w....w                                 ',
    '                     w....w w....w                                 ',
    '                     w....w w....w                                 ',
    '                     wwwwww wwwwww                                 ',
  ],
  things: [
    '',
    '                    ,   ,   , r ,       ,   ,   , r ,   $',
    '',
    '                                    O',
    '',
    '     ,,,        h                            =',
    '            r     d    m                    m   F       m   F',
    '    >                                                 u     J',
    '            M    r            M                     &',
    '  k       F                                                i',
    '                         s       r                    h',
    '                            h         h',
    '                        i                 i',
    '                                                   h  T  h',
    '                                            o                d',
    '                      o',
    '                                                S     h',
    '                                            r                   D',
    '                          i           !  s        i',
    '                                 r                        c     p',
    '                                 d              m           y',
    '',
    '                              @         i',
    '',
    '                      r                     k',
    '                     +',
    '',
    '                                       L     P',
    '                      d         d          r   !',
    '                           N',
    '                                      i         i',
    '                                         M',
    '                           4               c',
    '                       n       n                P',
    '                                     r     d     r',
    '                     X     p     X',
    '',
    '',
    '                       m r   r m',
    '                      $         $',
  ],
  triggers: [
    {
      on: 'start',
      do: [{ action: 'message', text: 'UP THE STAIRS AND INTO THE KITCHEN. IT SMELLS LIKE PIZZA UP HERE!' }],
    },
    {
      on: 'pickup',
      thing: 'pickup-soda-bazooka',
      do: [{ action: 'openDoors', tag: 'cupboards' }, { action: 'message', text: 'THE CUPBOARDS BURST OPEN! RATS!' }],
    },
  ],
});
