import { defineLevel } from '../../engine/defs.js';

// E1M3: THE LIVING ROOM. Couches, a fireplace, a big rug and a lot of rats.
//
// Route: the nook -> the living room -> the hall -> the bathroom (blue key)
// -> the blue door -> the den (red key; taking it sends Pack Rats down the
// chimney) -> the foyer -> the red door -> the stairs and the mouse hole.
// Secrets: the vent from the hall (a duct chamber with the Golden Cheese)
// and a bookshelf in the den that swings open.
export default defineLevel({
  id: 'e1m3',
  mapLabel: 'E1M3',
  name: 'THE LIVING ROOM',
  music: 'house',
  sky: 'sky-day',
  par: 150,
  legend: {
    h: { wall: 'door-wood' },
    c: { base: 'r', tag: 'chimney' },
    v: { door: 'bookshelf', secret: true },
    z: { base: 'm', secret: true },
    x: { base: ',', light: 210, secret: true },
  },
  tiles: [
    '                                                         ',
    '        #########N####h####N#########wwwwwwwwwwwwww      ',
    '        #...........................#.............w      ',
    '        #.........:::::::::.........#.....ttttttt.w      ',
    '        #.........:::::::::.........#.....ttttttt.w      ',
    '        #.........:::::::::.........3.....ttttttt.X      ',
    '        #.........:::::::::.........#.....ttttttt.w      ',
    '        #.........:::::::::.........#.....ttttttt.w      ',
    '        #...........................#.....ttttttt.w      ',
    '        #...........................#.............w      ',
    '        ####D######RRfffRR######D####wwwwwwwwwwwwww      ',
    '        B...........................B     wxxxxxxxw      ',
    '        B............c:c............B     wxxxxxxxw      ',
    '        B............:::............B     wxxxxxxxw      ',
    '        B...........................BwLLLLLLLLvLLLLLLLLww',
    '        B...........................B,,,,,,,,,,,,,,,,,,,w',
    '        B....rrrrrrrrrrrrrrrrrrr....a,,,,,,,,,,,,,,,,,,,w',
    '        B....rrrrrrrrrrrrrrrrrrr....B,,,,,,,,,,,,,,,,,,,w',
    ' #######B....rrrrrrrrrrrrrrrrrrr....B,,,,,,,,,,,,,,,,,,,w',
    ' #......B....rrrrrrrrrrrrrrrrrrr....B,,,,,;;;;;;;;;,,,,,w',
    ' #......B....rrrrrrrrrrrrrrrrrrr....B,,,,,;;;;;;;;;,,,,,w',
    ' #......B....rrrrrrrrrrrrrrrrrrr....B,,,,,;;;;;;;;;,,,,,w',
    ' #......D....rrrrrrrrrrrrrrrrrrr....1,,,,,;;;;;;;;;,,,,,w',
    ' #......B....rrrrrrrrrrrrrrrrrrr....B,,,,,;;;;;;;;;,,,,,w',
    ' #......B....rrrrrrrrrrrrrrrrrrr....B,,,,,;;;;;;;;;,,,,,w',
    ' #......B....rrrrrrrrrrrrrrrrrrr....B,,,,,;;;;;;;;;,,,,,w',
    ' #######B....rrrrrrrrrrrrrrrrrrr....B,,,,,,,,,,,,,,,,,,,w',
    '        B....rrrrrrrrrrrrrrrrrrr....B,,,,,,,,,,,,,,,,,,,w',
    '        B....rrrrrrrrrrrrrrrrrrr....B,,,,,,,,,,,,,,,,,,,w',
    ' VVVVVVVB....rrrrrrrrrrrrrrrrrrr....B,,,,,,,,,,,,,,,,,,,w',
    ' Vzzzzzzz....rrrrrrrrrrrrrrrrrrr....Bwwwwwwwwwwwwwwwwwwww',
    ' Vzzzzzzz....rrrrrrrrrrrrrrrrrrr....B                    ',
    ' Yzzzzzzz....rrrrrrrrrrrrrrrrrrr....B                    ',
    ' Vzzzzzzz...........................B                    ',
    ' Vzzzzzzz...........................B                    ',
    ' VVVVzVVB...........................B                    ',
    '    VnV B...........................B                    ',
    '    VnV B...........................B                    ',
    '    VnV BBBBBBNBBBBBBBDBBBBBBBNBBBBBB####                ',
    '    VnVVVVVVVV#.........................#                ',
    '    VnnnnnnnnnG.........................#                ',
    '    VVVVVVVVVV#.........................#                ',
    '              #####D##############D######                ',
    '              #,,,,,,,,,#   beeeeeeeeeeeb                ',
    '              #,,,,,,,,,#   beeeeeeeeeeeb                ',
    '              #,,,,,,,,,#   beeeeeeeeeeeb                ',
    '              #,,,,,,,,,#   beeeeeeeeeeeb                ',
    '              #,,,,,,,,,#   beeeeeeeeeeeb                ',
    '              #,,,,,,,,,#   beeeeeeeeeeeb                ',
    '              #,,,,,,,,,#   beeeeeeeeeeeb                ',
    '              ###########   bbbbbbbbbbbbb                ',
  ],
  things: [
    '',
    '',
    '',
    '          F d                     r     i       p',
    '              i',
    '                      m          N             G',
    '              E',
    '                              i               Z',
    '           r                           r    i',
    '                   k      &       F',
    '',
    '         o                         o        q   q',
    '          l                       l           D',
    '           d',
    '                          @',
    '            i                   i                      A',
    '                                      l               l',
    '                      H                     i',
    '                                      q             H',
    '  F',
    '            !     m       m     s             n   6',
    '     ,                c                               m',
    '   >           H             H          H     T',
    '     ,',
    '          F           r           F             j',
    '                      S                              `',
    '            s   r           r         c   E',
    '                                !           !     i',
    '                      V                 m             R',
    '           r                     r                 q',
    '     n           ;         ;',
    '   ;   ;      i               i',
    '     O',
    '   ;   ;  $           m',
    '                  Y',
    '                                 d',
    '          l                       l',
    '     ,   +',
    '     ,',
    '                $             r',
    '         , ,      r       M',
    '                          i           r',
    '',
    '',
    '                r                  d',
    '                M     r               m',
    '                 P            m',
    '                   p',
    '                     P            b',
    '                       B       i     ~',
  ],
  triggers: [
    { on: 'start', do: [{ action: 'message', text: 'THE LIVING ROOM. SO MANY COUCHES. SO MANY RATS.' }] },
    {
      on: 'pickup',
      thing: 'key-red',
      do: [
        { action: 'spawn', thing: 'pack-rat', tag: 'chimney' },
        { action: 'message', text: 'SOMETHING BIG JUST CAME DOWN THE CHIMNEY!' },
      ],
    },
  ],
});
