import { defineLevel } from '../../engine/defs.js';

// E1M4: UPSTAIRS. The kids' bedrooms, the bathroom and the playroom, where
// the floor really is LAVA.
//
// Route: the top of the stairs -> the hall -> the east bedroom (blue key) ->
// the blue door -> the playroom (yellow key on the island; taking it opens the
// toy boxes) -> the yellow door -> Mom and Dad's bedroom -> the attic stairs
// closet and the mouse hole. Rain boots in the pink bedroom and the playroom.
// Secrets: a closet behind the pink bedroom's north wall, and the bathroom
// vent (a duct chamber with the Golden Cheese).
export default defineLevel({
  id: 'e1m4',
  mapLabel: 'E1M4',
  name: 'UPSTAIRS',
  music: 'upstairs',
  sky: 'sky-day',
  par: 150,
  legend: {
    u: { base: 'p', tag: 'toybox' },
    q: { door: 'wallpaper-pink', secret: true },
    x: { base: ',', light: 176, secret: true },
    z: { base: 'm', secret: true },
  },
  tiles: [
    '                                                       ',
    '      PPPPPPPPP                                        ',
    '      PxxxxxxxP     ZZZZZZZZZZZZZZZZZZZZZ              ',
    '      PxxxxxxxP     ZupppppppppppppppppuZ              ',
    '      PxxxxxxxP     Zp~~ppppppppppppp~~pZ              ',
    '      PxxxxxxxP     Zp~~ppppppppppppp~~pZ              ',
    '      PPPPqPPPPPPPPPPpppppppppppppppppppZPPPNPPPPPNPPPP',
    '      P,,,,,,,,,,,,,Ppppp~~~~~~~~~~~ppppZ,,,,,,,,,,,,,P',
    '      P,,,,,,,,,,,,,Ppppp~~~~~~~~~~~ppppZ,,,,,,,,,,,,,P',
    '      P,,,,,,,,,,,,,Ppppp~~~~~~~~~~~ppppZ,,,,,,,,,,,,,P',
    '      N,,,,,,,,,,,,,Ppppp~~~ppppp~~~ppppZ,,,,,,,,,,,,,P',
    '      P,,,,,,,,,,,,,Ppppp~~~ppppp~~~ppppZ,,,,,,,,,,,,,P',
    '      P,,,,,,,,,,,,,Ppppp~~~ppppp~~~ppppZ,,,,,,,,,,,,,P',
    '      P,,,,,,,,,,,,,Ppppp~~~~~p~~~~~ppppZ,,,,,,,,,,,,,P',
    '      P,,,,,,,,,,,,,Ppppp~~~~~~~~~~~ppppZ,,,,,,,,,,,,,P',
    '      P,,,,,,,,,,,,,Ppppp~~~~~p~~~~~ppppZ,,,,,,,,,,,,,P',
    '      N,,,,,,,,,,,,,PpppppppppppppppppppZ,,,,,,,,,,,,,P',
    '      P,,,,,,,,,,,,,Pp~~ppppppppppppp~~pZ,,,,,,,,,,,,,P',
    '      P,,,,,,,,,,,,,Pp~~ppppppppppppp~~pZ,,,,,,,,,,,,,P',
    '      P,,,,,,,,,,,,,PpppppppppppppppppppZ,,,,,,,,,,,,,P',
    '      PPPPPPPDPPPPPPPZZZZZZZZZ1ZZZZZZZZZZPPPPPPDPPPPPPP',
    '      #,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#',
    '      #,,;,,,,,;,,,,,;,,,,,;,,,,,;,,,,,;,,,,,;,,,,,;,,#',
    '      #,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#',
    '      ######D########Q#####,,,,,,,###########2#########',
    '      beeeeeeeeeeeb,,,,,#...........#,,,,,,,,,,,,,,,,,W',
    '      beeeeeeeeeeeb,,,,,#...........#,,,,,,,,,,,,,,,,,W',
    '      beeeeeeeeeeeb,,,,,#...........#,,,,,,,,,,,,,,,,,W',
    '      beeeeeeeeeeeb,,,,,#...........#,,,,,,,,,,,,,,,,,W',
    '  VVVVbeeeeeeeeeeeb,,,,,#...........#,,,,;;;;;;;;;,,,,W',
    '  VzzzGeeeeeeeeeeeb######...........#,,,,;;;;;;;;;,,,,W',
    '  VzVVbeeeeeeeeeeeb     #...........#,,,,;;;;;;;;;,,,,W',
    '  VzV beeeeeeeeeeeb     #...........#,,,,;;;;;;;;;,,,,N',
    '  VzV beeeeeeeeeeeb     #...........#,,,,;;;;;;;;;,,,,W',
    '  VzV bbbbbbbbbbbbb     ######a######,,,,;;;;;;;;;,,,,W',
    '  VzV                               W,,,,;;;;;;;;;,,,,W',
    '  VzV                               W,,,,,,,,,,,,,,,,,W',
    '  VzV                               W,,,,,,,,,,,,,,,,,W',
    ' VVzVVVVVV                          W,,,,,,,,,,,,,,,,,W',
    ' VzzzzzzzV                          W,,,,,,,,,,,,,,,,,W',
    ' VzzzzzzzV                          WWWWAWWWWWEWWWWWWWW',
    ' VzzzzzzzY                                wtttttttw    ',
    ' VzzzzzzzV                                wtttttttw    ',
    ' VzzzzzzzV                                wtttttttw    ',
    ' VVVVVVVVV                                wtttttttw    ',
    '                                          wwwwXwwww    ',
  ],
  things: [
    '',
    '',
    '',
    '        p ; ;                 `',
    '            e             P        C',
    '                              c',
    '',
    '',
    '        Y         w  S                 p  Y         n',
    '           s 3 s        t                         b',
    '                      m     z         m     i   c',
    '                              y',
    '        @       r               z         n    r    d',
    '                      r               r',
    '          r                                  C',
    '        E        C     j             j     J       i',
    '             m                                 4',
    '                                          r      z',
    '         P     z  =       r   w   r          &      L',
    '                        Y           Y',
    '',
    '        L           i     !                       r',
    '          r t                      $  r     d',
    '                s                         i          F',
    '',
    '                                                     X',
    '         d      ,   s s   ,       ,   l             l',
    '                                          m',
    '              m      B7          M             G   E',
    '                   P        "         d',
    '            ~                           r         r  n',
    '',
    '          r    p              ^              T',
    '   ,    +                F         F    t         L',
    '                                      i',
    '   ,                                         c',
    '                                                    i',
    '                                         $  r',
    '                                       %         m  p',
    '                                     X',
    '   ;   ;',
    '     O',
    '   ;   ;',
    '     N                                      ,   ,',
  ],
  triggers: [
    {
      on: 'start',
      do: [{ action: 'message', text: 'UPSTAIRS. THE KIDS SAY THE PLAYROOM FLOOR IS LAVA. THEY ARE RIGHT.' }],
    },
    {
      on: 'pickup',
      thing: 'rain-boots',
      do: [{ action: 'message', text: 'RAIN BOOTS! NOW YOU CAN WALK ON THE LAVA (FOR A WHILE).' }],
    },
    {
      on: 'pickup',
      thing: 'key-yellow',
      do: [
        { action: 'spawn', thing: 'ninja-rat', tag: 'toybox' },
        { action: 'message', text: 'THE TOY BOXES BURST OPEN! NINJA RATS!' },
      ],
    },
  ],
});
