import { defineLevel } from '../../engine/defs.js';

// E1M5: THE ATTIC. Dad has come up to set mousetraps. Beat him and the house
// is yours (it ends the episode).
//
// Route: up the attic stairs, grab the Mega Microwave by the door, then
// take on Dad among the boxes. Soda bottles explode: use them!
// Secret: a vent behind the west wall.
export default defineLevel({
  id: 'e1m5',
  mapLabel: 'E1M5',
  name: 'THE ATTIC',
  music: 'upstairs',
  sky: 'sky-day',
  par: 180,
  legend: { a: { base: 't', tag: 'arena' }, z: { base: 'm', secret: true } },
  tiles: [
    '                                           ',
    '                                           ',
    '                                           ',
    '                                           ',
    '    wwwwwwwwwwwwNwwwwwwAwwwwwwNwwwwwwwwwwww',
    '    wtttttttttttttttttttttttttttttttttttttw',
    '    wtttttttttttttttttttttttttttttttttttttw',
    'VVV wtttttttttttttttttttttttttttttttttttttw',
    'VzV wtttttttttttttttttttttttttttttttttttttw',
    'VzV wtttttttttttttttttttttttttttttttttttttw',
    'VzV wtttttttttaaaaaaaaaaaaaaaaaaatttttttttw',
    'VzV wtttttttttaaaaaaaaaaaaaaaaaaatttttttttw',
    'VzV wtttttttttaaaaaaaaaaaaaaaaaaatttttttttw',
    'VzV wtttttttttaaaaaaaaaaaaaaaaaaatttttttttw',
    'VzV wtttttttttaaaaaaaaaaaaaaaaaaatttttttttw',
    'VzV wtttttttttaaaaaaaaaaaaaaaaaaatttttttttw',
    'VzVVwtttttttttaaaaaaaaaaaaaaaaaaatttttttttw',
    'VzzzGtttttttttaaaaaaaaaaaaaaaaaaatttttttttw',
    'VzVVwtttttttttaaaaaaaaaaaaaaaaaaatttttttttw',
    'VzV wtttttttttaaaaaaaaaaaaaaaaaaatttttttttw',
    'VzV wtttttttttaaaaaaaaaaaaaaaaaaatttttttttw',
    'VzV wtttttttttaaaaaaaaaaaaaaaaaaatttttttttw',
    'VzV wtttttttttaaaaaaaaaaaaaaaaaaatttttttttw',
    'VzV wtttttttttaaaaaaaaaaaaaaaaaaatttttttttw',
    'VzV wtttttttttaaaaaaaaaaaaaaaaaaatttttttttw',
    'VzV wtttttttttttttttttttttttttttttttttttttw',
    'VzV wtttttttttttttttttttttttttttttttttttttw',
    'VVV wtttttttttttttttttttttttttttttttttttttw',
    '    wtttttttttttttttttttttttttttttttttttttw',
    '    wtttttttttttttttttttttttttttttttttttttw',
    '    wwwwwwwwwwwwwwwwwwwEwwwwwwwwwwwwwwwwwww',
    '                  wtttttttttw              ',
    '                  wtttttttttw              ',
    '                  wtttttttttw              ',
    '                  wtttttttttw              ',
    '                  wtttttttttw              ',
    '                  wtttttttttw              ',
    '                  wtttttttttw              ',
    '                  wwwwwwwwwww              ',
  ],
  things: [
    '',
    '',
    '',
    '',
    '',
    '',
    '      n J                               n',
    '',
    '        XX      $             $       X',
    '',
    ' O        r                         r',
    '',
    '                       K                p',
    ' ;',
    '            o                     o',
    ' ;',
    '',
    '',
    '      p   N                         N',
    ' ;',
    '',
    ' ;',
    '            o                     o',
    '',
    ' D',
    '          r                         r',
    '        X                            XX',
    '                     Q 5 Q',
    '      n                                 n',
    '                     *   Z',
    '',
    '',
    '                       a',
    '                    d     d',
    '',
    '                       ^',
  ],
  triggers: [
    { on: 'start', do: [{ action: 'message', text: 'THE ATTIC. SOMEONE IS UP HERE, SETTING MOUSETRAPS...' }] },
    {
      on: 'enter',
      tag: 'arena',
      do: [{ action: 'music', id: 'boss' }, { action: 'message', text: 'DAD: WHO LET A RAT IN MY ATTIC?!' }],
    },
    { on: 'killed', thing: 'dad', do: [{ action: 'finale' }] },
  ],
});
