import { defineLevel } from '../../engine/defs.js';

// E2M1: THE LOADING DOCK. You fell asleep in a cardboard box and woke up in
// the back of a delivery truck, parked at a big warehouse.
//
// Route: out of the truck -> the yard (Slingshot) -> a dock door -> the
// receiving office (blue key) -> the blue door -> the racks (Rubber Band
// Gatling, yellow key at the end of the top aisle) -> the yellow door -> the
// shipping hall -> the mouse hole. The break room is off the dock; a vent
// joins it to the yard.
// Secrets: a crate that slides away in the fort in the yard (the Soda
// Bazooka) and a loose panel at the corner of the vent (a duct full of
// goodies).
export default defineLevel({
  id: 'e2m1',
  mapLabel: 'E2M1',
  name: 'THE LOADING DOCK',
  music: 'warehouse',
  sky: 'sky-day',
  par: 120,
  legend: {
    B: { wall: 'corrugated' },
    '#': { wall: 'cinderblock' },
    S: { wall: 'rack-boxes' },
    C: { wall: 'crates' },
    X: { wall: 'mouse-hole-block', use: 'exit', switchTo: 'mouse-hole-block-on' },
    L: { door: 'dock-door', jamb: 'concrete-stripe' },
    D: { door: 'door-metal', jamb: 'door-jamb' },
    '1': { door: 'door-metal-blue', jamb: 'door-jamb', lock: 'blue' },
    '2': { door: 'door-metal-yellow', jamb: 'door-jamb', lock: 'yellow' },
    '3': { door: 'door-metal-red', jamb: 'door-jamb', lock: 'red' },
    '.': { floor: 'warehouse-floor', ceiling: 'roof-truss', light: 192 },
    ':': { floor: 'warehouse-floor', ceiling: 'skylight', light: 228 },
    '-': { floor: 'warehouse-floor', ceiling: 'roof-truss', light: 160 },
    _: { floor: 'floor-stripe', ceiling: 'roof-truss', light: 192 },
    ',': { floor: 'asphalt', ceiling: 'sky', light: 232 },
    t: { floor: 'wood-floor', ceiling: 'roof-truss', light: 168 },
    q: { door: 'crates', secret: true },
    y: { door: 'vent-wall', secret: true },
    x: { base: '-', light: 176, secret: true },
    z: { base: 'm', secret: true },
  },
  thingLegend: { P: 'pallet', F: 'forklift', C: 'traffic-cone' },
  tiles: [
    'RRRRRRRRRRRRRRRRRRRRRRRBBBBBBBBBBBBBBB##########            ',
    'R,,,,,,,,,,,,,,,,,,,,,,B.._..........#kkkkkkkkk#            ',
    'R,,BBBBBBB,,,,,,,,,,,,,B.._..........#kkkkkkkkk#            ',
    'R,,BtttttB,,,,,,,,,,,,,B.._..:::.....#kkkjjjkkk#            ',
    'R,,BtttttB,,,,,,,,,,,,,B.._..:::.....#kkkjjjkkk#            ',
    'R,,BtttttB,,,,,,,,,,,,,L.._..:::.....Dkkkjjjkkk#            ',
    'R,,BtttttB,,,,,,,,,,,,,B.._..........#kkkkkkkkk#            ',
    'R,,BtttttB,,,,,,,,,,,,,B.._..........#kkkkkkkkk#            ',
    'R,,BtttttB,,,,,,,,,,,,,B.._..........#kkkkkkkkk#            ',
    'R,,BtttttB,,,,,,,,,,,,,B.._..........#######################',
    'R,,BtttttB,,,,,,,,,,,,,B.._..........#---------------------#',
    'R,,BtttttB,,,,,,,,,,,,,L.._..........#--------::::---------#',
    'R,,BtttttB,,,,,,,,,,,,,B.._..........#---------------------#',
    'R,,BtttttB,,,,,,,,,,,,,B.._..:::.....#---SSSSSSSSSSSSSSS---#',
    'R,,BtttttB,,,,,,,,,,,,,B.._..:::.....#---------------------#',
    'R,,BtttttB,,,,,,,,,,,,,B.._..:::.....#--------::::---------#',
    'R,,BtttttB,,,,,,,,,,,,,B.._..........#---------------------#',
    'R,,BtttttB,,,,,,,,,,,,,L.._..........#---SSSSSSSSSSSSSSS---#',
    'R,,,,,,,,,,,,,,,,,,,,,,B.._..........#---------------------#',
    'R,,,,,,,,,,,,,,,,,,,,,,B.._..........#--------::::---------#',
    'R,,,,,,,,,,,,,,,,,,,,,,B.._..........1---------------------#',
    'R,,,,,,,,,,,,,,,,,,,,,,B.._..........#---SSSSSSSSSSSSSSS---#',
    'R,,,,,,,,,,,,,,,,,,,,,,B.._..........#---------------------#',
    'R,,,,,,,,,,,,,,,,,,,,,,L.._..:::.....#--------::::---------#',
    'R,,,,,,,,,,,,,,,,,,,,,,B.._..:::.....#---------------------#',
    'RCCCCCCC,,,,,,,,,,,,,,,B.._..:::.....#---SSSSSSSSSSSSSSS---#',
    'RCxxxxxC,,,,,,,,,,,,,,,B.._..........#---------------------#',
    'RCxxxxxC,,,,,,,,,,,,,,,B.._..........#---------------------#',
    'RCxxxxxq,,,,,,,,,,,,,,,B.._..........#--------::::---------#',
    'RCxxxxxC,,,,,,,,,,,,,,,B.._..........#---------------------#',
    'RCxxxxxC,,,,,,,,,,,,,,,B######D#######---------------------#',
    'RCCCCCCC,,,,,,,,,,,,,,,#kkkkkkkkkkkkk###########2###########',
    'RRRRRRRRRRRRGRRRRRRRRRR#kkkkkkkkkkkkk#.....................#',
    '           VnV         #kkkkkkkkkkkkk#.....................#',
    '           VnV         #kkkkkkkkkkkkk#.....................#',
    '           VnV         #kkkkjjjjjkkkk#....CCC..............#',
    '           VnVVVVVVVVVV#kkkkjjjjjkkkk#....CCC..:::.........#',
    '           VnnnnnnnnnnnGkkkkjjjjjkkkk#....CCC..:::.........#',
    '        VVVVyVVVVVVVVVV#kkkkjjjjjkkkk#.........:::.........X',
    '        VzzzzzzzV      #kkkkjjjjjkkkk#.............CCC.....#',
    '        VzzzzzzzV      #kkkkkkkkkkkkk#.............CCC.....#',
    '        VzzzzzzzY      #kkkkkkkkkkkkk#.............CCC.....#',
    '        VzzzzzzzV      #kkkkkkkkkkkkk#.....................#',
    '        VzzzzzzzV      #kkkkkkkkkkkkk#.....................#',
    '        VVVVVVVVV      #kkkkkkkkkkkkk#.....................#',
    '                       #####################################',
  ],
  things: [
    '',
    '',
    '            P  P         P P       P   ";;   b',
    '    XX  X           i                      T',
    '      v X       2                 i',
    '                 M                        h',
    '            r',
    '                                       m    r',
    '       1          M         r    F            k',
    '    X',
    '      ,             C      M       m   p',
    '                                        s   r           my',
    '      , X       r        d',
    '',
    '    X ,             C              P',
    '                   $     @                          r    s',
    '                            o',
    '                                   J',
    '           C C C                r',
    '                                                  j      i',
    '  o       +   M                M  X',
    '                                   X',
    '  ;     !         r',
    '                                        m           r    s',
    '                                  &',
    '                                       %                 d',
    '                 o               i',
    '   N                     P         P        s   r        G',
    '    4         i     M   `     c                        c',
    '     n                                 3         a       S',
    '                   " k',
    '',
    '                                   d                     P',
    '                                                s       i',
    '            ,             r             $         i',
    '                              u',
    '            ,                                         o',
    '                ,   ,       h T h                   r',
    '                                       s',
    '',
    '          S   J          m',
    '            A',
    '                                        c              G',
    '          ;   ;          p        ,,          p',
    '                        e           k  P                 P',
  ],
  triggers: [
    {
      on: 'start',
      do: [{ action: 'message', text: 'YOU FELL ASLEEP IN A CARDBOARD BOX... AND WOKE UP IN A TRUCK! WHERE ARE WE?' }],
    },
    {
      on: 'pickup',
      thing: 'key-yellow',
      do: [{ action: 'message', text: 'THE YELLOW KEY! THE SHIPPING HALL IS SOUTH OF THE RACKS.' }],
    },
  ],
});
