import { defineLevel } from '../../engine/defs.js';

// E2M2: THE AISLES. Rows and rows of shelves, stacked to the roof.
//
// Route: the entry -> the front aisles (Flare Gun and the blue key at the far
// east end) -> the blue door -> the back aisles (red key in the north-west
// corner) -> the red door -> the returns office -> the mouse hole. Rats
// climb out of the returns bins when you walk into the office.
// Secrets: a rack on the east wall that slides away (the Golden Cheese)
// and a vent in the back aisles' north wall (a duct loop over the roof, with a
// second vent cover back down into the back aisles).
export default defineLevel({
  id: 'e2m2',
  mapLabel: 'E2M2',
  name: 'THE AISLES',
  music: 'warehouse',
  sky: 'sky-day',
  par: 150,
  legend: {
    B: { wall: 'corrugated' },
    '#': { wall: 'cinderblock' },
    S: { wall: 'rack-boxes' },
    C: { wall: 'crates' },
    X: { wall: 'mouse-hole-block', use: 'exit', switchTo: 'mouse-hole-block-on' },
    L: { door: 'dock-door', jamb: 'concrete-stripe' },
    D: { door: 'door-metal', jamb: 'door-jamb' },
    '1': { door: 'door-metal-blue', jamb: 'door-jamb', lock: 'blue' },
    '2': { door: 'door-metal-yellow', jamb: 'door-jamb', lock: 'yellow' },
    '3': { door: 'door-metal-red', jamb: 'door-jamb', lock: 'red' },
    '.': { floor: 'warehouse-floor', ceiling: 'roof-truss', light: 192 },
    ':': { floor: 'warehouse-floor', ceiling: 'skylight', light: 228 },
    '-': { floor: 'warehouse-floor', ceiling: 'roof-truss', light: 160 },
    _: { floor: 'floor-stripe', ceiling: 'roof-truss', light: 192 },
    ',': { floor: 'asphalt', ceiling: 'sky', light: 232 },
    t: { floor: 'wood-floor', ceiling: 'roof-truss', light: 168 },
    F: { wall: 'freezer-wall' },
    W: { wall: 'cheese-shelf' },
    J: { door: 'freezer-door', jamb: 'freezer-wall' },
    i: { floor: 'ice-floor', ceiling: 'freezer-ceiling', light: 176 },
    l: { floor: 'ice-floor', ceiling: 'freezer-light', light: 220 },
    M: { wall: 'machine' },
    U: { wall: 'chute' },
    '^': { floor: 'conveyor-n', ceiling: 'roof-truss', light: 192, push: [0, -2.5] },
    v: { floor: 'conveyor-s', ceiling: 'roof-truss', light: 192, push: [0, 2.5] },
    '>': { floor: 'conveyor-e', ceiling: 'roof-truss', light: 192, push: [2.5, 0] },
    '<': { floor: 'conveyor-w', ceiling: 'roof-truss', light: 192, push: [-2.5, 0] },
    K: { wall: 'log-wall' },
    A: { wall: 'barn-wood' },
    s: { floor: 'sawdust', ceiling: 'sky', light: 232 },
    h: { floor: 'sawdust', ceiling: 'roof-truss', light: 176 },
    q: { door: 'rack-boxes', secret: true },
    x: { base: '-', light: 176, secret: true },
    z: { base: 'm', secret: true },
    a: { base: '.', tag: 'office' },
    w: { base: '.', tag: 'bins' },
  },
  thingLegend: { P: 'pallet', F: 'forklift', C: 'traffic-cone', L: 'log-pile', K: 'lumberjack' },
  tiles: [
    '                                       VVVVVVVVVVVVVVVVVVVVVVVVV',
    '                                       VzzzzzzzzzzzzzzzzzzzzzzzV',
    '                                       VzVVVVVVVVVVVVVVVVVzzzzzV',
    '########################################G#################zzzzzV',
    '#.................#--------------------------------------#zzzzzY',
    '#.................#--------------------------------------#zzzzzV',
    '#..............w..#--------------------------------------GzzzzzV',
    '#.................#---SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS---#zzzzzV',
    '#...aaaaaaa.......#--------------------------------------#VVVVVV',
    '#...aaaaaaa.......#-------::----------::----------::-----#      ',
    '#...aaaaaaa.......#--------------------------------------#      ',
    '#...aaaaaaa.......#---SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS---#      ',
    '#...aaaaaaa.......#--------------------------------------#      ',
    'X...aaaaaaa.......3--------------------------------------#      ',
    '#...aaaaaaa.......#--------------------------------------#      ',
    '#...aaaaaaa.......#---SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS---#      ',
    '#.w.aaaaaaa.......#--------------------------------------#      ',
    '#...aaaaaaa.......#-------::----------::----------::-----#      ',
    '#...aaaaaaa.....w.#--------------------------------------#      ',
    '#.................#---SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS---#      ',
    '#.................#--------------------------------------#      ',
    '#.................#--------------------------------------#      ',
    '#.................#--------------------------------------#      ',
    '#######################################1##################      ',
    '#.................#--------------------------------------#      ',
    '#.................#--------------------------------------#      ',
    '#.................#-----S-----S-----S-----S-----S--------S      ',
    '#.................#-----S-----S-----S-----S-----S--------S      ',
    '#.....::::::......#--:--S--:--S--:--S--:--S--:--S---:----S      ',
    '#.....::::::......#--:--S--:--S--:--S--:--S--:--S---:----S      ',
    '#.....::::::......D--:--S--:--S--:--S--:--S--:--S---:----S      ',
    '#.....::::::......#-----S-----S-----S-----S-----S--------S      ',
    '#.....::::::......#-----S-----S-----S-----S-----S--------S      ',
    '#.....::::::......#-----S-----S-----S-----S-----S--------S      ',
    '#.................#--------------------------------------S      ',
    '#.................#--------------------------------------S      ',
    '#.................#-----S-----S-----S-----S-----S--------S######',
    '#.................#-----S-----S-----S-----S-----S--------Sxxxxx#',
    '###################-----S-----S-----S-----S-----S--------Sxxxxx#',
    '#.................#--:--S--:--S--:--S--:--S--:--S---:----Sxxxxx#',
    '#.................#--:--S--:--S--:--S--:--S--:--S---:----qxxxxx#',
    '#.................#--:--S--:--S--:--S--:--S--:--S---:----Sxxxxx#',
    '#.................#-----S-----S-----S-----S-----S--------Sxxxxx#',
    '#.................D-----S-----S-----S-----S-----S--------Sxxxxx#',
    '#.................#--------------------------------------S######',
    '#.................#--------------------------------------S      ',
    '#.................#______________________________________#      ',
    '#.................#--------------------------------------#      ',
    '##########################################################      ',
  ],
  things: [
    '',
    '                                             ,    ,   ,',
    '',
    '                                                            D',
    '                    R',
    '  P             P        r        s         %          m   ; ;',
    '',
    '                                                             r',
    '',
    '   d        r       i         G                r       p',
    '',
    '',
    '',
    '       T h     i        E          r  c         E      i',
    '',
    '',
    '             u',
    '                    !       m       &     s         r',
    '',
    '    r',
    '              XX',
    '  P                 d          r            i     !    Z',
    '',
    '',
    '                                                   b',
    '  XX            X    r     $        o        i         6',
    '      ;;;;                       i',
    '              m      M                 r',
    '',
    '',
    '        A                        s           s      r',
    '    r',
    '                           r',
    '                     `                 E',
    '             r                                  c      m',
    '     J    p                   c     !',
    '  X                  d     s',
    '                                             r',
    '                                                    @      Z',
    '  P',
    '            r                    r     M                    O',
    '        ,,,          m',
    '                                                    i        Z',
    '   >                                         $',
    '                           r     S     m',
    '           s         E',
    '      +       r                           o        M',
    '  P            P          X   F             Xd        E',
  ],
  triggers: [
    { on: 'start', do: [{ action: 'message', text: 'THE AISLES. SHELVES, SHELVES, SHELVES... AND RATS.' }] },
    {
      on: 'pickup',
      thing: 'pickup-flare-gun',
      do: [{ action: 'message', text: 'A FLARE GUN! LIGHT UP THOSE DARK AISLES.' }],
    },
    {
      on: 'enter',
      tag: 'office',
      do: [
        { action: 'message', text: 'RATS ARE CLIMBING OUT OF THE RETURNS BINS!' },
        { action: 'spawn', thing: 'rat', tag: 'bins' },
      ],
    },
  ],
});
