import { defineLevel } from '../../engine/defs.js';

// E2M3: THE BIG FREEZER. A walk-in freezer the size of a house, full of
// frozen cheese.
//
// Route: the antechamber -> the cheese vault -> the ice hall (Blow Torch,
// blue key at the east end) -> the blue door -> the blast chiller (yellow
// key) -> back through the vault -> the yellow door -> the loading tunnel
// -> the mouse hole.
// Secrets: a cheese shelf in the vault's south wall that swings open (the
// deep freeze) and a vent in the antechamber's north wall (a duct room).
export default defineLevel({
  id: 'e2m3',
  mapLabel: 'E2M3',
  name: 'THE BIG FREEZER',
  music: 'basement',
  sky: 'sky-day',
  par: 150,
  legend: {
    B: { wall: 'corrugated' },
    '#': { wall: 'cinderblock' },
    S: { wall: 'rack-boxes' },
    C: { wall: 'crates' },
    X: { wall: 'mouse-hole-block', use: 'exit', switchTo: 'mouse-hole-block-on' },
    L: { door: 'dock-door', jamb: 'concrete-stripe' },
    D: { door: 'door-metal', jamb: 'door-jamb' },
    '1': { door: 'door-metal-blue', jamb: 'door-jamb', lock: 'blue' },
    '2': { door: 'door-metal-yellow', jamb: 'door-jamb', lock: 'yellow' },
    '3': { door: 'door-metal-red', jamb: 'door-jamb', lock: 'red' },
    '.': { floor: 'warehouse-floor', ceiling: 'roof-truss', light: 192 },
    ':': { floor: 'warehouse-floor', ceiling: 'skylight', light: 228 },
    '-': { floor: 'warehouse-floor', ceiling: 'roof-truss', light: 160 },
    _: { floor: 'floor-stripe', ceiling: 'roof-truss', light: 192 },
    ',': { floor: 'asphalt', ceiling: 'sky', light: 232 },
    t: { floor: 'wood-floor', ceiling: 'roof-truss', light: 168 },
    F: { wall: 'freezer-wall' },
    W: { wall: 'cheese-shelf' },
    J: { door: 'freezer-door', jamb: 'freezer-wall' },
    i: { floor: 'ice-floor', ceiling: 'freezer-ceiling', light: 176 },
    l: { floor: 'ice-floor', ceiling: 'freezer-light', light: 220 },
    M: { wall: 'machine' },
    U: { wall: 'chute' },
    '^': { floor: 'conveyor-n', ceiling: 'roof-truss', light: 192, push: [0, -2.5] },
    v: { floor: 'conveyor-s', ceiling: 'roof-truss', light: 192, push: [0, 2.5] },
    '>': { floor: 'conveyor-e', ceiling: 'roof-truss', light: 192, push: [2.5, 0] },
    '<': { floor: 'conveyor-w', ceiling: 'roof-truss', light: 192, push: [-2.5, 0] },
    K: { wall: 'log-wall' },
    A: { wall: 'barn-wood' },
    s: { floor: 'sawdust', ceiling: 'sky', light: 232 },
    h: { floor: 'sawdust', ceiling: 'roof-truss', light: 176 },
    q: { door: 'cheese-shelf', secret: true },
    x: { base: 'i', secret: true },
    z: { base: 'm', secret: true },
  },
  thingLegend: { P: 'pallet', F: 'forklift', C: 'traffic-cone', L: 'log-pile', K: 'lumberjack' },
  tiles: [
    'VVVVVVVVVVVVFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                 ',
    'VzzzzzzzzzzzFiiiiiiiiiiiiiiiiiiiiiiiiiiiF                 ',
    'VzzzzzzzzzzzFiiiiiiiiiiiiiiiiiiiiiiiiiiiF                 ',
    'VzzzzzzzzzzzFiiiiiiiiiiiiiiiiiiiiiiiiiiiF                 ',
    'VzzzzzzzzzzzFiiiiiiiiiiiiiiiiiiiiiiiiiiiF                 ',
    'VzzzzzzzzzzzFiiiliiiiiiiiiliiiiiiiiiliiiF                 ',
    'VzzzzzzzzzzzFiiiiiiiiiiiiiiiiiiiiiiiiiiiF                 ',
    'VzzzzzzzzzzzFiiiiiiiiiiiiiiiiiiiiiiiiiiiF                 ',
    'VzzzzzzzzzzzFiiiiiiiiiiiiiiiiiiiiiiiiiiiF                 ',
    'VVVVVVzVVVVVFiiiiiiiiiiiiiiiiiiiiiiiiiiiF                 ',
    '     VzV    FFFFFFFFFFFFFFJFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
    '     VzV    FiiiiiiiiiiiiiiiiiiiiiiiiiiiFllllllllllllllllF',
    '     VzV    FiiiiiiiiiiiliiiiiiiiiiiliiiFllllllllllllllllF',
    '     VzV    FiiiiiiiiiiiliiiiiiiiiiiliiiFllllllllllllllllY',
    '     VzV    FiiiWWWWWWWiliWWWWWWWiiiliiiFllllllllllllllllF',
    '     VzV    FiiiWWWWWWWiliWWWWWWWiiiliiiFllllllllllllllllF',
    '     VzV    FiiiiiiiiiiiliiiiiiiiiiiliiiFllllllllllllllllF',
    '     VzV    Fiiiiiiiiiiiliiiiiiiiiiiliii1llllllllllllllllF',
    '######G#####FiiiiiiiiiiiliiiiiiiiiiiliiiFllllllllllllllllF',
    '#...........FiiiiiiiiiiiliiiiiiiiiiiliiiFllllllllllllllllF',
    '#...........FiiiWWWWWWWiliWWWWWWWiiiliiiFllllllllllllllllY',
    '#...........FiiiWWWWWWWiliWWWWWWWiiiliiiFllllllllllllllllF',
    '#...........FiiiiiiiiiiiliiiiiiiiiiiliiiFllllllllllllllllF',
    '#...........JiiiiiiiiiiiliiiiiiiiiiiliiiFllllllllllllllllF',
    '#...........FiiiiiiiiiiiliiiiiiiiiiiliiiFIIIIIIIIIIIIIIIIF',
    '#...........FiiiiiiiiiiiliiiiiiiiiiiliiiF----------------O',
    '#...........FiiiWWWWWWWiliWWWWWWWiiiliiiF----------------O',
    '#...........FiiiWWWWWWWiliWWWWWWWiiiliiiF----------------O',
    '############FiiiiiiiiiiiliiiiiiiiiiiliiiF---..........---O',
    '            FiiiiiiiiiiiliiiiiiiiiiiliiiF---..........---O',
    '            Fiiiiiiiiiiiliiiiiiiiiiiliii2---..........---X',
    '            FiiiWWWWWWWiliWWWWWWWiiiliiiF---..........---O',
    '            FiiiWWWWWWWiliWWWWWWWiiiliiiF---..........---O',
    '            FiiiiiiiiiiiliiiiiiiiiiiliiiF----------------O',
    '            FiiiiiiiiiiiliiiiiiiiiiiliiiF----------------O',
    '            FiiiiiiiiiiiiiiiiiiiiiiiiiiiF----------------O',
    '            FFWWWWWWqWWWWWWWWFFFFFFFFFFFFOOOOOOOOOOOOOOOOO',
    '            FxxxxxxxxxxxxxxxxxF                           ',
    '            FxxxxxxxxxxxxxxxxxF                           ',
    '            FxxxxxxxxxxxxxxxxxF                           ',
    '            FxxxxxxxxxxxxxxxxxF                           ',
    '            FxxxxxxxxxxxxxxxxxF                           ',
    '            FxxxxxxxxxxxxxxxxxF                           ',
    '            FxxxxxxxxxxxxxxxxxF                           ',
    '            FxxxxxxxxxxxxxxxxxF                           ',
    '            FFFFFFFFFFFFFFFFFFF                           ',
  ],
  things: [
    '',
    '                                 d',
    '   Z     ;              i     &       b',
    '                    j',
    '      p',
    '                    t     `   t    r',
    '         ;       r',
    '                                j',
    '              7                       m',
    '',
    '',
    '',
    '      ,       r         G          i d      m          *',
    '                         s',
    '                                                  c',
    '      ,',
    '',
    '                   ;    r    ;   s              J     y',
    '              !                   M  m',
    ' P        s',
    '                                             j',
    '      ,,,                                           G',
    '                                          p',
    '   >               E         t    r',
    '              r         m',
    '         r                               P',
    '    +                                         S        i',
    ' P         P',
    '                                     $       r',
    '              s    t              c',
    '                        r          n            d    G',
    '',
    '',
    '                                  @               r',
    '              i                      r      %',
    '              d         E                P              P',
    '',
    '',
    '',
    '                     N     *',
    '                A',
    '',
    '                         S',
    '              d             d',
  ],
  triggers: [
    {
      on: 'start',
      do: [
        { action: 'message', text: 'BRRRR! THE BIG FREEZER.' },
        { action: 'message', text: 'MILES AND MILES OF CHEESE... ALL FROZEN.' },
      ],
    },
    {
      on: 'pickup',
      thing: 'pickup-blow-torch',
      do: [{ action: 'message', text: 'A BLOW TORCH! THAT WILL WARM THINGS UP.' }],
    },
  ],
});
