import { defineLevel } from '../../engine/defs.js';

// E2M4: THE CONVEYOR BELTS. The sorting room, where every box in the
// warehouse rides the belts. The belts carry you along too.
//
// Route: the intake room -> the sorting floor -> the sorting island (blue
// key; every belt around it runs outward, so push against them) -> the blue
// door -> the packing room (ride the belt up to the Mega Microwave, yellow
// key in the corner) -> the yellow door -> the dispatch bay -> ride the
// belt to the mouse hole.
// Secrets: a chute in the intake room's east wall (the lost parcels) and a
// vent in the dispatch bay's west wall (a duct room).
export default defineLevel({
  id: 'e2m4',
  mapLabel: 'E2M4',
  name: 'THE CONVEYOR BELTS',
  music: 'warehouse',
  sky: 'sky-day',
  par: 150,
  legend: {
    B: { wall: 'corrugated' },
    '#': { wall: 'cinderblock' },
    S: { wall: 'rack-boxes' },
    C: { wall: 'crates' },
    X: { wall: 'mouse-hole-block', use: 'exit', switchTo: 'mouse-hole-block-on' },
    L: { door: 'dock-door', jamb: 'concrete-stripe' },
    D: { door: 'door-metal', jamb: 'door-jamb' },
    '1': { door: 'door-metal-blue', jamb: 'door-jamb', lock: 'blue' },
    '2': { door: 'door-metal-yellow', jamb: 'door-jamb', lock: 'yellow' },
    '3': { door: 'door-metal-red', jamb: 'door-jamb', lock: 'red' },
    '.': { floor: 'warehouse-floor', ceiling: 'roof-truss', light: 192 },
    ':': { floor: 'warehouse-floor', ceiling: 'skylight', light: 228 },
    '-': { floor: 'warehouse-floor', ceiling: 'roof-truss', light: 160 },
    _: { floor: 'floor-stripe', ceiling: 'roof-truss', light: 192 },
    ',': { floor: 'asphalt', ceiling: 'sky', light: 232 },
    t: { floor: 'wood-floor', ceiling: 'roof-truss', light: 168 },
    F: { wall: 'freezer-wall' },
    W: { wall: 'cheese-shelf' },
    J: { door: 'freezer-door', jamb: 'freezer-wall' },
    i: { floor: 'ice-floor', ceiling: 'freezer-ceiling', light: 176 },
    l: { floor: 'ice-floor', ceiling: 'freezer-light', light: 220 },
    M: { wall: 'machine' },
    U: { wall: 'chute' },
    '^': { floor: 'conveyor-n', ceiling: 'roof-truss', light: 192, push: [0, -2.5] },
    v: { floor: 'conveyor-s', ceiling: 'roof-truss', light: 192, push: [0, 2.5] },
    '>': { floor: 'conveyor-e', ceiling: 'roof-truss', light: 192, push: [2.5, 0] },
    '<': { floor: 'conveyor-w', ceiling: 'roof-truss', light: 192, push: [-2.5, 0] },
    K: { wall: 'log-wall' },
    A: { wall: 'barn-wood' },
    s: { floor: 'sawdust', ceiling: 'sky', light: 232 },
    h: { floor: 'sawdust', ceiling: 'roof-truss', light: 176 },
    q: { door: 'chute', secret: true },
    x: { base: '-', light: 176, secret: true },
    z: { base: 'm', secret: true },
  },
  thingLegend: { P: 'pallet', F: 'forklift', C: 'traffic-cone', L: 'log-pile', K: 'lumberjack' },
  tiles: [
    '#########################                                   ',
    '#.............#xxxxxxxxx#                                   ',
    '#.............#xxxxxxxxx#                                   ',
    '#.............#xxxxxxxxx#                                   ',
    '#.............#xxxxxxxxx#                                   ',
    '#.............#xxxxxxxxx#                                   ',
    '#.............qxxxxxxxxx#                                   ',
    '#.............#xxxxxxxxx#                                   ',
    '#.............#xxxxxxxxx#                                   ',
    '#.............#xxxxxxxxx#                                   ',
    '#.............#xxxxxxxxx#                                   ',
    '#.............###########                                   ',
    '#######D################U#######U#######U###################',
    '#...........................................#..............#',
    '#...........................................#..:::::::::...#',
    '#...........................................#......^.......#',
    '#.>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>..#......^.......#',
    '#...........................................#......^.......#',
    '#...........................................#......^.......#',
    '#...........................................#......^.......#',
    '#...<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<.#......^.......#',
    '#...........................................#......^.......#',
    '#...........................................#......^.......#',
    '#...........................................#......^.......#',
    '#......^^^^^^^^^^^..........................1......^.......#',
    '#......<:::::::::>........MMMMMMMMM.........#......^.......#',
    '#......<:::::::::>........MMMMMMMMM.........#......^.......#',
    '#......<:::::::::>........MMMMMMMMM.........#......^.......#',
    '#......<:::::::::>........MMMMMMMMM.........#......^.......#',
    '#......<:::::::::>........MMMMMMMMM.........#......^.......#',
    '#......<:::::::::>........MMMMMMMMM.........#......^.......#',
    '#......<:::::::::>..........................#......^.......#',
    '#......vvvvvvvvvvv..........................#......^.......#',
    '#...........................................#..............#',
    '##############################2#############################',
    '              B...............................B             ',
    '              B...........:::::::::...........B             ',
    '              B...........:::::::::...........B             ',
    'VVVVVVVVVV    B...........:::::::::...........B             ',
    'VzzzzzzzzV    B...............................B             ',
    'VzzzzzzzzV    B.>>>>>>>>>>>>>>>>>>>>>>>>>>>>>.X             ',
    'YzzzzzzzzVVVVVB...............................B             ',
    'VzzzzzzzzzzzzzG...............................B             ',
    'VzzzzzzzzVVVVVB...............................B             ',
    'VzzzzzzzzV    B...............................B             ',
    'VVVVVVVVVV    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB             ',
  ],
  things: [
    '',
    '',
    '  XX        X   Q     Q',
    '       v',
    '',
    '                   O',
    '     , , ,',
    '',
    '    +',
    '           r    X     X',
    '  X         s',
    '',
    '',
    ' X                                        d      q 5 q    X',
    '     r  s           r         i         $                 X',
    '                                                        i',
    '                                              r',
    '',
    '  m       C   $ M     o     J     s r   o        j      %',
    '',
    '                                               T       T',
    '                                      M',
    '   E        r           m     G',
    '                                        r     m      p',
    '                                    @                   r',
    '',
    '                    s                 c',
    '                                               T       T',
    '  i         b         c                   i',
    '             ;',
    '                                                      c',
    '                     !  P                  X    r',
    '                         E          m r                  y',
    ' d  `                 r                    X X S',
    '',
    '               P                             P',
    '                      Q                     i',
    '                  r         c       j',
    '                                          &',
    '  Z   ,',
    '',
    '    A',
    '           ,        &         d',
    '                        r       G       r',
    '  Z   ,        Pi                 Q       E',
  ],
  triggers: [
    {
      on: 'start',
      do: [
        { action: 'message', text: 'THE SORTING ROOM. WATCH YOUR STEP:' },
        { action: 'message', text: 'THE CONVEYOR BELTS CARRY YOU ALONG!' },
      ],
    },
    {
      on: 'pickup',
      thing: 'key-blue',
      do: [{ action: 'message', text: 'GOT IT! NOW RIDE THE BELTS BACK OUT.' }],
    },
  ],
});
