import { defineLevel } from '../../engine/defs.js';

// E2M5: THE LUMBER YARD. The Lumberjack works out back. Beat him and his
// chainsaw is yours, and the sawmill shed opens.
//
// Route: the back room (Mega Microwave) -> the yard: fight the Lumberjack
// among the log piles -> grab the chainsaw he drops -> the sawmill shed
// (its barn door opens when he falls) -> the mouse hole ends the episode.
// Secrets: a gap in the west log wall (a nook behind the woodpile) and a
// vent in the back room's west wall (a duct room).
export default defineLevel({
  id: 'e2m5',
  mapLabel: 'E2M5',
  name: 'THE LUMBER YARD',
  music: 'warehouse',
  sky: 'sky-day',
  par: 180,
  legend: {
    B: { wall: 'corrugated' },
    '#': { wall: 'cinderblock' },
    S: { wall: 'rack-boxes' },
    C: { wall: 'crates' },
    X: { wall: 'mouse-hole-block', use: 'exit', switchTo: 'mouse-hole-block-on' },
    L: { door: 'dock-door', jamb: 'concrete-stripe' },
    D: { door: 'door-metal', jamb: 'door-jamb' },
    '1': { door: 'door-metal-blue', jamb: 'door-jamb', lock: 'blue' },
    '2': { door: 'door-metal-yellow', jamb: 'door-jamb', lock: 'yellow' },
    '3': { door: 'door-metal-red', jamb: 'door-jamb', lock: 'red' },
    '.': { floor: 'warehouse-floor', ceiling: 'roof-truss', light: 192 },
    ':': { floor: 'warehouse-floor', ceiling: 'skylight', light: 228 },
    '-': { floor: 'warehouse-floor', ceiling: 'roof-truss', light: 160 },
    _: { floor: 'floor-stripe', ceiling: 'roof-truss', light: 192 },
    ',': { floor: 'asphalt', ceiling: 'sky', light: 232 },
    t: { floor: 'wood-floor', ceiling: 'roof-truss', light: 168 },
    F: { wall: 'freezer-wall' },
    W: { wall: 'cheese-shelf' },
    J: { door: 'freezer-door', jamb: 'freezer-wall' },
    i: { floor: 'ice-floor', ceiling: 'freezer-ceiling', light: 176 },
    l: { floor: 'ice-floor', ceiling: 'freezer-light', light: 220 },
    M: { wall: 'machine' },
    U: { wall: 'chute' },
    '^': { floor: 'conveyor-n', ceiling: 'roof-truss', light: 192, push: [0, -2.5] },
    v: { floor: 'conveyor-s', ceiling: 'roof-truss', light: 192, push: [0, 2.5] },
    '>': { floor: 'conveyor-e', ceiling: 'roof-truss', light: 192, push: [2.5, 0] },
    '<': { floor: 'conveyor-w', ceiling: 'roof-truss', light: 192, push: [-2.5, 0] },
    K: { wall: 'log-wall' },
    A: { wall: 'barn-wood' },
    s: { floor: 'sawdust', ceiling: 'sky', light: 232 },
    h: { floor: 'sawdust', ceiling: 'roof-truss', light: 176 },
    e: { door: 'barn-wood', jamb: 'barn-wood', lock: 'remote', tag: 'shed' },
    q: { door: 'log-wall', secret: true },
    x: { base: 's', secret: true },
    y: { base: 's', tag: 'yard' },
    z: { base: 'm', secret: true },
  },
  thingLegend: { P: 'pallet', F: 'forklift', C: 'traffic-cone', L: 'log-pile', K: 'lumberjack' },
  tiles: [
    '                      ##########X##########                 ',
    '                      AhhhhhhhhhhhhhhhhhhhA                 ',
    '                      AhhhhhhhhhhhhhhhhhhhA                 ',
    '                      AhhhhhhhhhhhhhhhhhhhA                 ',
    '                      AhhhhhhhhhhhhhhhhhhhA                 ',
    '                      AhhhhhhhhhhhhhhhhhhhA                 ',
    '                      AhhhhhhhhhhhhhhhhhhhA                 ',
    '                      AhhhhhhhhhhhhhhhhhhhA                 ',
    '    KKKKKKKKKKKKKKKKKKAAAAAAAAAAeAAAAAAAAAAKKKKKKKKKKKKKKKKK',
    '    KssssssssssssssssssssssssssssssssssssssssssssssssssssssK',
    '    KssssssssssssssssssssssssssssssssssssssssssssssssssssssK',
    '    KssssssssssssssssssssssssssssssssssssssssssssssssssssssK',
    '    KssssssssssssssssssssssssssssssssssssssssssssssssssssssK',
    '    KssssssssssssssssssssssssssssssssssssssssssssssssssssssK',
    '    KsssssssKKKKssssssssssssssssssssssssssssssssKKKKsssssssK',
    '    KsssssssKKKKssssssssssssssssssssssssssssssssKKKKsssssssK',
    '    KsssssssKKKKssssssssssssssssssssssssssssssssKKKKsssssssK',
    '    KssssssssssssssssssssssssssssssssssssssssssssssssssssssK',
    'KKKKKssssssssssssssssssssssssssssssssssssssssssssssssssssssK',
    'KxxxKssssssssssssssssssssssssssssssssssssssssssssssssssssssK',
    'KxxxKssssssssssssssssssssssssssssssssssssssssssssssssssssssK',
    'KxxxKssssssssssssssssssssssssKKKKKKKsssssssssssssssssssssssK',
    'KxxxqssssssssssssssssssssssssKKKKKKKsssssssssssssssssssssssK',
    'KxxxKssssssssssssssssssssssssKKKKKKKsssssssssssssssssssssssK',
    'KxxxKssssssssssssssssssssssssssssssssssssssssssssssssssssssK',
    'KxxxKssssssssssssssssssssssssssssssssssssssssssssssssssssssK',
    'KKKKKssssssssssssssssssssssssssssssssssssssssssssssssssssssK',
    '    KsssssssKKKKssssssssssssssssssssssssssssssssKKKKsssssssK',
    '    KsssssssKKKKssssssssssssssssssssssssssssssssKKKKsssssssK',
    '    KsssssssKKKKssssssssssssssssssssssssssssssssKKKKsssssssK',
    '    KssssssssssssssssssssssssssssssssssssssssssssssssssssssK',
    '    KssssssssssssssssssssssssssssssssssssssssssssssssssssssK',
    '    KssssssssssssssssssssssssssssssssssssssssssssssssssssssK',
    '    KssssssssssssssssssssssyyyyyyyyyyysssssssssssssssssssssK',
    '    KssssssssssssssssssssssyyyyyyyyyyysssssssssssssssssssssK',
    '    KssssssssssssssssssssssyyyyyyyyyyysssssssssssssssssssssK',
    '    KKKKKKKKKKKKKKKKKKKKKK######L######KKKKKKKKKKKKKKKKKKKKK',
    '            VVVVVVVV      #...........#                     ',
    '            VzzzzzzV      #...........#                     ',
    '            VzzzzzzVVVVVVV#...........#                     ',
    '            YzzzzzzzzzzzzzG...........#                     ',
    '            VzzzzzzVVVVVVV#...........#                     ',
    '            VzzzzzzV      #...........#                     ',
    '            VVVVVVVV      #############                     ',
  ],
  things: [
    '',
    '',
    '                          p           p',
    '                        L               L',
    '',
    '',
    '',
    '                       X                 X',
    '',
    '',
    '      Q r         m                           m         rQ',
    '',
    '                    L                       L',
    '                                K',
    '',
    '',
    '        *                                               S',
    '',
    '                        L               L',
    '                                d',
    '  Q      L          q                       q          L',
    '',
    '  A       !   p                                   p   @',
    '',
    '  p               r                           r',
    '',
    '                                %',
    '                        L               L',
    '',
    '',
    '                                c',
    '                    L                       L',
    '                                a',
    '         L                                             L',
    '      i Q           N   $               $   N            i',
    '',
    '',
    '                           P',
    '              d              5 ,,, Q',
    '',
    '               Q     , ,      S    Q',
    '                                ^',
    '                 d          d       d',
  ],
  triggers: [
    {
      on: 'start',
      do: [
        { action: 'message', text: 'THE LUMBER YARD, BEHIND THE WAREHOUSE.' },
        { action: 'message', text: 'SOMEBODY OUT THERE IS CHOPPING WOOD...' },
      ],
    },
    {
      on: 'enter',
      tag: 'yard',
      do: [
        { action: 'music', id: 'boss' },
        { action: 'message', text: 'THE LUMBERJACK: HEY! NO RATS IN MY LUMBER YARD!' },
      ],
    },
    {
      on: 'killed',
      thing: 'lumberjack',
      do: [
        { action: 'openDoors', tag: 'shed' },
        { action: 'message', text: 'THE SAWMILL SHED IS OPEN. THE WAY OUT IS IN THERE!' },
      ],
    },
  ],
});
